# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "121a2iilk99s4zcqbpxn58ks8fml0x2lvbif7gpsh2rq68mz5ryq";
    x86_64-linux = "1wy589i7hw5f82ynzlhs9a2w2sqhqsixzzdp9inc1h1g9nn30xgr";
    armv6l-linux = "14cbxwcjbgcggvr3dwyzmdpgpaw8hcldpvqbih6aqfi5q4q7q454";
    armv7l-linux = "0ijxhg26frj9jw52yhixgjdjiqv5f1s8xl7blaapcfvlvm45f19k";
    aarch64-linux = "055fjjlxpnl6s04kmzcclfhr5mf1ij5dy548b8wp46mj99qmwp2v";
    x86_64-darwin = "0hv35fx01xcqizjqjcrfa25yynbr84sw4h7avlmsflbz16dhl81f";
    aarch64-darwin = "1rc7bqk9031pyikpl35idp7l3wa7kl91nal78dvp59mm514pi0ml";
  };

  urlMap = {
    i686-linux = "https://github.com/complex-gh/seedify/releases/download/v1.16.0/seedify_1.16.0_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/complex-gh/seedify/releases/download/v1.16.0/seedify_1.16.0_Linux_x86_64.tar.gz";
    armv6l-linux = "https://github.com/complex-gh/seedify/releases/download/v1.16.0/seedify_1.16.0_Linux_armv6.tar.gz";
    armv7l-linux = "https://github.com/complex-gh/seedify/releases/download/v1.16.0/seedify_1.16.0_Linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/complex-gh/seedify/releases/download/v1.16.0/seedify_1.16.0_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/complex-gh/seedify/releases/download/v1.16.0/seedify_1.16.0_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/complex-gh/seedify/releases/download/v1.16.0/seedify_1.16.0_Darwin_arm64.tar.gz";
  };
  sourceRootMap = {
    i686-linux = "seedify_1.16.0_Linux_i386";
    x86_64-linux = "seedify_1.16.0_Linux_x86_64";
    armv6l-linux = "seedify_1.16.0_Linux_armv6";
    armv7l-linux = "seedify_1.16.0_Linux_armv7";
    aarch64-linux = "seedify_1.16.0_Linux_arm64";
    x86_64-darwin = "seedify_1.16.0_Darwin_x86_64";
    aarch64-darwin = "seedify_1.16.0_Darwin_arm64";
  };
in
stdenvNoCC.mkDerivation {
  pname = "seedify";
  version = "1.16.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./seedify $out/bin/seedify
    installManPage ./manpages/seedify.1.gz
    installShellCompletion ./completions/*
  '';

  meta = {

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv6l-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
