# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "1dvphicwv5zc4lnpqd51cpqaj9myj59ph9zaawgcscb90dwh1wkq";
    x86_64-linux = "0c5j4ypnpdr59b1mzddccs8is04khzlpk15lyvsp5isdb8mrn925";
    armv6l-linux = "08immvd4865z2kvp5y2d82imya9042nyxm37vyal6wb6cxi87mww";
    armv7l-linux = "0g92ahn13livm007hfr7xs1f46d3hdagyfi6rgmk846dgpgkaj35";
    aarch64-linux = "1n7yqbhq6sm0jhf570igh2f2vcx97aj0m0mykcdz280c3xa6r13z";
    x86_64-darwin = "0dq1y460fv6jv7nfpz4hrg2ray20n6glka2rbha10vbp7piw9szd";
    aarch64-darwin = "1v3xvixpv8lc23ar0xcilf6dw7iwq2y6pn093wr68kk4zpl3hzz2";
  };

  urlMap = {
    i686-linux = "https://github.com/complex-gh/seedify/releases/download/v1.0.1/seedify_1.0.1_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/complex-gh/seedify/releases/download/v1.0.1/seedify_1.0.1_Linux_x86_64.tar.gz";
    armv6l-linux = "https://github.com/complex-gh/seedify/releases/download/v1.0.1/seedify_1.0.1_Linux_armv6.tar.gz";
    armv7l-linux = "https://github.com/complex-gh/seedify/releases/download/v1.0.1/seedify_1.0.1_Linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/complex-gh/seedify/releases/download/v1.0.1/seedify_1.0.1_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/complex-gh/seedify/releases/download/v1.0.1/seedify_1.0.1_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/complex-gh/seedify/releases/download/v1.0.1/seedify_1.0.1_Darwin_arm64.tar.gz";
  };
  sourceRootMap = {
    i686-linux = "seedify_1.0.1_Linux_i386";
    x86_64-linux = "seedify_1.0.1_Linux_x86_64";
    armv6l-linux = "seedify_1.0.1_Linux_armv6";
    armv7l-linux = "seedify_1.0.1_Linux_armv7";
    aarch64-linux = "seedify_1.0.1_Linux_arm64";
    x86_64-darwin = "seedify_1.0.1_Darwin_x86_64";
    aarch64-darwin = "seedify_1.0.1_Darwin_arm64";
  };
in
stdenvNoCC.mkDerivation {
  pname = "seedify";
  version = "1.0.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./seedify $out/bin/seedify
    installManPage ./manpages/seedify.1.gz
    installShellCompletion ./completions/*
  '';

  meta = {

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv6l-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
